# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-30 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('foodType', models.CharField(choices=[('IC', 'Ice Cream'), ('CK', 'Cakes'), ('SW', 'Sweets')], max_length=20)),
                ('desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
